### ISSUE TITLE
Doesn't seem to work with reflex 0.6.6

### ISSUE THREAD

**Issue by dentroai** [masenf/reflex-audio-capture#7]
Works fine with reflex 0.6.0, but with 0.6.6 the `on_data_available` never seems to be called when running `capture.stop()`.

**Comment by chi1337** [comment]
I have observed the same thing in 0.6.7, on_data_available is not called. Would be great if this issue is fixed.

**Comment by masenf** [comment]
should be fixed in v0.0.5, available now for reflex 0.6.6+

**Comment by dentroai** [comment]
Great, can confirm 0.0.5 works with reflex 0.6.7, thank you !
